### ISSUE TITLE
[버그 수정]: Writing 모달 실행 시 오류가 납니다.

### ISSUE THREAD

**Issue by shyuuuuni** [boostcampwm-2022/web06-WeView#131]
### 설명

```
@react-refresh:278 Uncaught Error: Unknown language: ""
    at _highlight (core.js:2101:13)
    at Object.highlight2 [as highlight] (core.js:1726:9)
    at CodeEditor.tsx:14:12
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)
```

관련 코드를 살펴보니 처음 language 값이 "" 로 들어가서 CodeEditor useEffect의 hljs.highlight 함수 실행 시 오류가 나는 것 같아요.

language가 선택되지 않았을 때 기본 옵션을 적용한다거나 하는 방식으로 수정할 수 있을 것 같아요.

**Comment by shyuuuuni** [comment]
작업하다보니까 language HTML에 넣고, hello world가 입력되서 잘 되는 것 같습니다. 왜 떳지?
